export const CURRICULUM_TOPICS: Record<string, string[]> = {
  dsa: [
    "Arrays",
    "Sorting",
    "Hashing",
    "Strings",
    "Binary Search",
    "Recursion",
    "Linked-List",
    "Bit Manipulation",
    "Sliding Window / 2 Pointer",
    "Stack / Queues",
    "Greedy Algorithms",
    "Binary Trees",
    "Binary Search Trees",
    "Heaps",
    "Graphs",
    "Dynamic Programming",
    "Tries",
    "Strings (Advanced Algo)",
    "Maths",
  ],
  oops: [
    "Introduction to OOPS",
    "Core Principles of OOPS",
    "Advance OOPS features",
    "Relationships and Object Behaviour",
    "Advance Programming in OOPS",
    "OOP Design and Lifecycle Management",
  ],
  dbms: [
    "Getting Started",
    "DBMS Foundations and Architecture",
    "Core Foundations",
    "Conceptual Data Modeling",
    "Database Design",
    "Relational Model and Formal Query Languages",
    "Functional Dependencies and Database Design",
    "Querying Essentials",
    "Aggregation and Analysis",
    "Set Operations",
    "SQL Joins",
    "Subqueries",
    "Data Modification and Schema Evolution",
    "Physical Storage, Indexing, and Hashing",
    "Data Storage, Keys, and Query Optimization",
    "Query Processing and Optimization",
    "Query Performance",
    "Transactions and Access Control",
    "Transactions and Concurrency Control",
    "Database Recovery and Durability",
    "Integrity, Security, and Database Operations",
    "Distributed Databases, NoSQL, and Analytical Systems",
    "Applied Learning and Preparation",
  ],
  "operating-systems": [
    "Module-1 (Operating System Basics and OS Introduction)",
    "Module-2 (Process Management in Operating System)",
    "Module-3 (CPU Scheduling Algorithms in Operating System)",
    "Module-4 (Kernel, OS Structures, and Advanced Scheduling)",
    "Module-5 (Threads and Multithreading in Operating System)",
    "Module-6 (Process Synchronization and Concurrency Control)",
    "Module-7 (Deadlock, Starvation, and Concurrency Bugs)",
  ],
  "computer-networks": [
    "Module-1 (CN Foundations)",
    "Module-2 (Network Models)",
    "Module-3 (Physical and Data Link Layer)",
    "Module-4 (Network Topologies and VLANs)",
    "Module-5 (Network Layer: IP Addressing)",
    "Module-6 (Network Layer: Routing)",
    "Module-7 (Transport Layer)",
    "Module-8 (Application Layer)",
    "Module-9 (NAT and Internet Edge Networking)",
    "Module-10 (Switching Techniques)",
    "Module-11 (Network Security)",
    "Module-12 (Cryptography and Secure Protocols)",
    "Module-13: (Wireless Networking)",
    "Module-14 (Network Performance)",
    "Module-15 (Situation Based Explanations)",
  ],
  lld: [
    "Introduction to LLD",
    "Solid Principles",
    "UML",
    "Creational Design Patterns",
    "Structural Design Patterns",
    "Behavioural Design Patterns",
    "Multithreading and Concurrency",
    "Dependency Injection",
    "Exceptions and Error Handling",
    "Best practices in LLD",
    "Interview Problems (Part-1)",
    "Interview Problems (Part-2)",
    "Interview Problems (Part-3)",
  ],
};
